lib/app.js
package-lock.json
package.json

* bumped asl-service to 2.6.0
* updated breadcrumbs to use content keys rather than strings

Abstracted content

---

.drone.yml
tests/functional/specs/smoke-tests.js

Post-deploy tests are failing for a number of reasons:
* selenium wasn't running in drone
* there was a case mismatch in the tests

Fix post deploy tests

---

lib/app.js
package-lock.json
package.json

* updated crumbs variables to take values from static
* take pages from asl-pages
* updated asl-service to 3.0.0 and installed asl-pages 2.0.0

Use ASL-Pages

---

.babelrc
.drone.yml
.gitignore
lib/app.js
package-lock.json
package.json
webpack.config.js

* bumped asl-service to 3.1.2 and pages to 3.0.0
* installed webpack and babel deps
* added webpack.config which points to asl-service/webpack.config
* updated routes

Updated to compile assets in main project

---

.eslintignore
assets/sass/app.scss
lib/app.js
package-lock.json
package.json

This incorporates the latest css fixes.
Also compile css in app for consistency with `asl`

Use latest service and pages versions

---

.drone.yml
.kube.yaml
Dockerfile
assets/sass/app.scss
config.js
lib/app.js
lib/errors/index.js
lib/errors/not-authorised.js
lib/errors/not-found.js
lib/middleware/workflow.js
package-lock.json
package.json
pages/dashboard/content/index.js
pages/dashboard/index.js
pages/dashboard/views/index.jsx
tests/functional/config.js
tests/functional/specs/smoke-tests.js

Moves establishment list to `/establishments` and adds a (very basic) task list to the dashboard page.

Add ASRU user dashboard

---

tests/functional/config.js

"inspector" has changed to "internal" in the deployed urls

Fix test urls

---

config.js
package-lock.json

One to file under "how on earth did this ever work?"

Add configuration for permissions service

---

lib/app.js
package-lock.json
package.json
pages/dashboard/content/index.js
pages/dashboard/index.js
pages/dashboard/views/index.jsx

This was supposed to be just using the feedback page, but updating to the new pages broke the existing dashboard/task list, so that needed to be fixed too to get anything to work.
~This will need https://github.com/UKHomeOffice/asl-pages/pull/169 to be merged and published.~

Revive dashboard

---

lib/app.js
package-lock.json
package.json
pages/establishment-list/content/index.js
pages/establishment-list/index.js
pages/establishment-list/schema/index.js
pages/establishment-list/views/index.jsx

This page only ever appears in this project, so should not be loaded from @asl/pages
Will remove the corresponding page from @asl/pages once this is shipped.

Move establishment list page into this repo

---

lib/app.js
lib/urls.js
pages/profile/content/index.js
pages/profile/index.js
pages/profile/views/index.jsx
pages/search/views/index.jsx

Adds an empty page that allows asru users to see the profile of any user within the system, irrespective of establishment affiliations.

Add global profile page

---

pages/components/search-panel/content.js
pages/search/content/projects.js
pages/search/schema/projects.js
pages/search/views/index.jsx

Adds a search result page for the projects.

Add project search results

---

pages/search/views/index.jsx

For consistency with other links to establishments in people and project search results.

Link establishment search results to the establishment dashboard

---

pages/profile/components/asru-roles.jsx

We need a way to be able to inspect this in integration tests.

Add a `className` to ASRU roles list component

---

pages/profile/content/index.js
pages/profile/views/index.jsx

Loop over the user's establishments and render a profile component for each establishment

Add establishment-profile components to global profile page

---

pages/project-versions/read/views/index.jsx

Rename link to task view

---

.drone.yml
package-lock.json

There is a high level vulnerability that has no current mitigation. However, it is in a dev dependency that does not run on production infrastructure so is considered tolerable.

Increase failure level on audit to critical

---

pages/reporting/index.js
pages/reporting/lib/nts-summary.js

I hadn't actually _run_ my latest code version when I created the PR.

Remove merge of missing table row

---

package-lock.json
package.json
pages/reporting/index.js

Using the project title as the file name is all fun and games until someone puts a `/` in an it starts making folders.

Remove slashes from file paths

---

pages/profile/components/toggle-asru.jsx
pages/profile/content/index.js

Add missing warning to asru user management

---

.drone.yml

The high level vulns that previously had no mitigation are now mitigated.

Set vulnerability level back to high (default)

---

pages/profile/index.js

This is needed to render profile page breadcrumb labels

Add profile data to static on global profile page

---

package-lock.json
package.json
pages/dashboard/views/index.jsx

Update tasklist - now controls own props

---

pages/profile/views/index.jsx

ASRU want to be able to know if a particular user has ever accessed their account. This does that.

Add a "Has login" flag to user profile page

---

lib/urls.js

This was partly refactored but missed.

Fix account update url

---

lib/app.js
lib/urls.js
package-lock.json
package.json
pages/establishment/content/index.js
pages/establishment/create/content/index.js
pages/establishment/create/index.js
pages/establishment/create/schema/index.js
pages/establishment/create/views/index.jsx
pages/establishment/index.js
pages/search/content/index.js
pages/search/views/index.jsx

~Waiting on internal-api PR https://github.com/UKHomeOffice/asl-internal-api/pull/44~

Add create establishment functionality

---

lib/routes.js
pages/search/index.js
pages/search/search.js

* added router and param function to root of search

Improve search routing

---

pages/reporting/views/index.jsx

Also split PPL iterations into old and new style applications

Add Project revoke and PIL transfer to metrics page

---

pages/asru-assignment/index.js

This didn't have a body parser bound to it before, so is throwing an error in production.

Add body-parser to ASRU unassignment route

---

package-lock.json
package.json
pages/reporting/lib/nts-summary.js

The docx version didn't align with the way this was working with Word tables.

Fix NTS summary export

---

pages/reporting/lib/nts-summary.js

Otherwise too much exists at a global level and I can't be bothered working out what needs to not be. At the very least it's the abstract numbering for `ol`s.

Move all the code into the function scope

---

package-lock.json
package.json
pages/project/update-issue-date/schema/index.js

Use a function to define date validtion cut off so that the comparator date is re-evaluated each time the validator function is called and not just on server start-up, which leads to validation behaving incorrectly on long-running server instances.

Fix date validation

---

package-lock.json
package.json
pages/search/views/index.jsx

Needs
* https://github.com/UKHomeOffice/asl-components/pull/103
* https://github.com/UKHomeOffice/asl-pages/pull/669

Hide countdown if licence isn't active

---

package-lock.json
package.json
pages/search/schema/establishments.js
pages/search/search.js
pages/search/views/index.jsx

* Added link filter to global search if filter options are returned from api
* Default to active if not set
WIP until ~https://github.com/UKHomeOffice/asl-components/pull/105 and~ https://github.com/UKHomeOffice/asl-internal-api/pull/52

Global search status filter

---

package-lock.json
package.json
pages/profile/content/index.js
pages/profile/index.js
pages/profile/views/index.jsx

Allows an ASRU user to see any tasks raised either by or about a person.

Add tasklist component to ASRU profile page

---

lib/app.js
package-lock.json
package.json

New desktop footer (internal):
New mobile footer (internal):
New desktop footer (external):

New footer sections

---

lib/routes.js
package-lock.json
package.json
pages/common/content/index.js
pages/revoke-establishment/content/confirm.js
pages/revoke-establishment/content/index.js
pages/revoke-establishment/index.js
pages/revoke-establishment/routers/confirm.js
pages/revoke-establishment/routers/update.js
pages/revoke-establishment/schema/index.js
pages/revoke-establishment/views/confirm.jsx
pages/revoke-establishment/views/index.jsx
pages/revoke-establishment/views/success.jsx

waiting on https://github.com/UKHomeOffice/asl-pages/pull/697

Revoke a PEL

---

package-lock.json
package.json
pages/common/content/index.js
pages/project/index.js
pages/project/routes.js
pages/project/update-licence-number/content/confirm.js
pages/project/update-licence-number/content/index.js
pages/project/update-licence-number/index.js
pages/project/update-licence-number/routers/confirm.js
pages/project/update-licence-number/routers/update.js
pages/project/update-licence-number/schema/index.js
pages/project/update-licence-number/views/confirm.jsx
pages/project/update-licence-number/views/index.jsx

~Waiting on https://github.com/UKHomeOffice/asl-pages/pull/727~

Allow update of licence number for project stubs

---

package-lock.json
package.json
pages/search/views/index.jsx

~waiting on https://github.com/UKHomeOffice/asl-pages/pull/743~

Use projectTitle formatter from pages in list view

---

package-lock.json
package.json
pages/search/views/index.jsx

Also bump pages for improvements to the legacy project conversion feature.

Rename stub to partial record

---

lib/routes.js
package-lock.json
package.json

~WIP until https://github.com/UKHomeOffice/asl-pages/pull/764~

Feature - PIL list

---

lib/app.js
lib/routes.js
package-lock.json
package.json
pages/common/content/index.js
pages/downloads/content/index.js
pages/downloads/index.js
pages/downloads/views/index.jsx
pages/reporting/downloads/index.js
pages/reporting/downloads/tasks-by-week.js
pages/reporting/index.js
pages/reporting/views/index.jsx

Creates the new downloads page with links to NTS downloads and also links to new tasks processed by type/date report.
The tasks processed report is a little speculative because I don't have good data locally. Will need testing on preprod and prod.

Add tasks report and ASRU downloads page

---

pages/nts/lib/renderers/v1.js

Render the elements selected from the checkbox list which now forms the the question without being wrapped in a radio group.

Fix fate of animals section in NTS download document

---

assets/sass/wide.scss
package-lock.json
package.json

* bumped schema
* added wide.scss

Feature - widescreen

---

pages/search/views/index.jsx

* Title case project status
* Updated transferred filter to transferred out

Bugfix - titlecase status on project search

---

package-lock.json
package.json

* Remove hanging } in download links
* Fix docx to the correct version

Fix NTS downloads

---

lib/routes.js
pages/global-profile/content/index.js
pages/global-profile/index.js
pages/licence-fees/establishments/views/index.jsx

* adds permissions checks to the downloads and reporting routes
* adds support as an option in the roles management UI

New Asru support user type

---

lib/routes.js
pages/reporting-beta/content/index.js
pages/reporting-beta/downloads/index.js
pages/reporting-beta/downloads/tasks-by-week.js
pages/reporting-beta/index.js
pages/reporting-beta/views/index.jsx

Uses XHR to load potentially slow-loading data dynamically on change of filter date so that perceived responsiveness and performance is improved.

Add beta version of the metrics page which uses metrics service

---

.drone.yml
pages/reporting/download/index.js
pages/reporting/routes.js

Additionally run docker build on all builds so that unbuildable versions cannot be merged

Add missing files

---

pages/search/content/establishments.js
pages/search/content/index.js
pages/search/content/profiles.js
pages/search/content/projects.js
pages/search/views/index.jsx

* Updated project search list to use status labels rather than plain text
* extend ppl content from pages
* use status formatter from pages

Feature - RA labels

---

package-lock.json
package.json
pages/revoke-establishment/index.js
pages/revoke-establishment/routers/confirm.js
pages/revoke-establishment/views/success.jsx

~waiting on https://github.com/UKHomeOffice/asl-pages/pull/876~

Generic success

---

lib/routes.js

This should be scoped to a profile

Bugfix - fix route for training

---

package-lock.json
pages/downloads/views/index.jsx
pages/reporting/index.js

~waiting on https://github.com/UKHomeOffice/asl-metrics/pull/28~

Add download link to establishment report

---

package-lock.json
package.json
pages/components/search-panel/index.jsx

* Bumped components with aria-labelledby for search input
* Use h2 for label - "search"

Accessibility - search label

---

package-lock.json
package.json
pages/nts/lib/rich-text.js

Modify the NTS export rich text editor to handle object values.

Use raw data structures for rich text

---

lib/app.js
lib/routes.js
pages/asru-profiles-list/content/index.js
pages/asru-profiles-list/index.js
pages/asru-profiles-list/schema/index.js
pages/asru-profiles-list/views/index.jsx
pages/common/content/index.js

~needs https://github.com/UKHomeOffice/asl-internal-api/pull/86~

Staff directory page with search

---

pages/reporting/index.js

What even are numbers

---

package-lock.json
package.json
pages/reporting/index.js
pages/reporting/views/index.jsx

These got dropped by accident in the rebuild

Restore PPL iteration counts to metrics page

---

pages/reporting/views/index.jsx

Fix key for application counts

---

package-lock.json
package.json
pages/search/views/index.jsx

~Waiting on https://github.com/UKHomeOffice/asl-pages/pull/1050~

Pass result type to the FilterSummary for custom label

---

assets/sass/app.scss
pages/components/search-panel/content.js
pages/search/content/establishments.js
pages/search/content/index.js
pages/search/content/profiles.js
pages/search/formatters/index.jsx
pages/search/schema/establishments.js
pages/search/schema/profiles.js
pages/search/views/index.jsx

* Support filtering profiles with no associated establishments
* Highlight search term matches in results
* Various improvements to wording
* Various styling improvements

Search improvements

---

pages/search/content/profiles.js
pages/search/formatters/index.jsx
pages/search/schema/profiles.js

PIL number was also missing from the results, added it.

Better search highlighting

---

pages/dashboard/content/index.js
pages/search/content/index.js

This was throwing an error because the source file moved, but doesn't seem to cause any issue if removed completely.
Also updated header on advanced project search page to match designs.

Remove broken require of content

---

assets/sass/app.scss
pages/reporting/index.js
pages/reporting/views/index.jsx

Needs https://github.com/UKHomeOffice/asl-metrics/pull/59 before it will start showing any different figures in the UI.

Add tabs for filtering tasks on initiatedByAsru

---

lib/app.js
lib/routes.js

* added ra routes
* bumped pages and projects

Feature - RA

---

pages/search/views/index.jsx

* Added all-inactive status which groups revoked, expired and transferred

Feature - group inactive proj statuses

---

pages/reporting/content/index.js
pages/reporting/views/index.jsx

Add RA's completed to perf metrics page

---

pages/reporting/download/content/index.js
pages/reporting/download/index.js

As well as loading the tasks and segmenting by week also include the PPL expiration data in the CSV download.

Add PPL expirations to CSV download of performance metrics

---

lib/routes.js
package-lock.json
package.json
pages/cjsm/content/index.js
pages/cjsm/index.js
pages/cjsm/schema/index.js
pages/cjsm/views/index.jsx

* bumped pages with CJSM link on est dashboard
* added cjsm update form

Feature - CJSM

---

pages/reporting/details/routes.js
pages/reporting/details/task-list/content/index.js
pages/reporting/details/task-list/index.js
pages/reporting/details/task-list/report-filters.js
pages/reporting/details/task-list/schema/index.js
pages/reporting/details/task-list/views/index.jsx
pages/reporting/index.js
pages/reporting/metrics-filter-form.js
pages/reporting/views/components/initiated-by-filter.jsx
pages/reporting/views/components/metrics-filter.jsx
pages/reporting/views/components/task-counts.jsx
pages/reporting/views/index.jsx

waiting on 
* ~https://github.com/UKHomeOffice/asl-internal-api/pull/91~

Link metrics to details page with list of matching tasks

---

pages/cjsm/content/index.js
pages/cjsm/schema/index.js

This prevent downstream errors if the value doesn't fit the prescribed format to be inserted into the database.

Add basic email address validation for CJSM

---

package-lock.json
package.json
pages/downloads/reports/index.js
pages/reporting/download/index.js

To allow utf8 to render correctly in Excel

Add BOM to CSV exports

---

pages/components/dashboard-navigation.jsx

* link to active ests for est search by default

Feature - default to active ests

---

pages/rops/index.js

~needs https://github.com/UKHomeOffice/asl-internal-api/pull/100~

Get rops summary data from api instead of metrics

---

pages/search/content/projects.js
pages/search/formatters/index.jsx
pages/search/schema/projects.js

* Replaced expiryDate with endDate

Feature - end date for proj search

---

pages/reporting/content/index.js
pages/reporting/views/index.jsx

* Added rop submit tasks to metrics page

Feature- add rops to metrics

---

pages/rops/establishments/content/index.js
pages/rops/establishments/schema/index.js

* Added rops overdue to est table

Feature - rops overdue

---

assets/sass/app.scss
package-lock.json
package.json
pages/search/content/projects-content.js
pages/search/index.js
pages/search/views/components/filters.jsx
pages/search/views/index.jsx

* Bumped components with changes to filters
* Removed link filter for project content sesarch
* Added filters component

Feature - project content search filters

---

pages/search/views/index.jsx

* only check values from status

bugfix - extra status filter

---

pages/rops/download/dictionary/index.js
pages/rops/download/dictionary/views/index.jsx
pages/rops/download/routes.js
pages/rops/download/views/index.jsx

* Added link to dictionary from rops download page
* Use schema to generate dictionary from content

Feature - rops dictionary

---

lib/routes.js
package-lock.json
package.json

~waiting on https://github.com/UKHomeOffice/asl-pages/pull/1332~

Show a breadcrumb on the rops reporting page

---

package-lock.json
package.json
pages/dashboard/views/index.jsx
pages/search/views/index.jsx

~needs https://github.com/UKHomeOffice/asl-pages/pull/1343 and https://github.com/UKHomeOffice/asl-components/pull/226~

Improved task list filters

---

pages/reporting/content/index.js
pages/reporting/details/task-list/content/index.js
pages/reporting/details/task-list/views/index.jsx

Mostly changing headings for the list of tasks by type.

Content updates to performance metrics pages

---

assets/sass/app.scss
package-lock.json
package.json
pages/asru-profiles-list/content/index.js
pages/global-profile/components/asru-actions.jsx
pages/global-profile/components/manage-roles.jsx
pages/global-profile/content/index.js

needs:
- https://github.com/UKHomeOffice/react-components/pull/62

More detailed summaries of ASRU roles

---

pages/rops/download/content/index.js
pages/rops/download/views/index.jsx

Needs:
- https://github.com/UKHomeOffice/asl-components/pull/243

Open data dictionary link in new tab

---

pages/rops/download/index.js
pages/rops/download/views/index.jsx

WIP pending content confirmation.

Auto refresh the rops download until it's ready then trigger

---

lib/app.js
lib/routes.js
pages/asru-profiles-list/index.js
pages/asru-workload/content/index.js
pages/asru-workload/index.js
pages/asru-workload/schema/index.js
pages/asru-workload/views/index.jsx
pages/common/content/index.js

needs:
- https://github.com/UKHomeOffice/asl-metrics/pull/97
- https://github.com/UKHomeOffice/asl-internal-api/pull/119

Add page for viewing staff workloads

---

pages/rops/index.js

Will come back to this with a clever fix, but for now this will do.

Hard code default ROPs year to 2021

---

pages/search/content/establishments.js
pages/search/schema/establishments.js

These don't have any values and are no longer used.

Remove inspector and SPOC from establishment search results

---

pages/enforcement/update/schema/index.js

The draft projects were being filtered from the list in the header but not from the actual checkboxes.

flaggable projects should not include drafts

---

package-lock.json
package.json
pages/search/content/establishments.js
pages/search/content/profiles.js
pages/search/formatters/index.jsx
pages/search/schema/profiles.js

Needs: 
- https://github.com/UKHomeOffice/asl-components/pull/259
- https://github.com/UKHomeOffice/asl-pages/pull/1499

Feature: suspend / reinstate licences

---

pages/asru-profiles-list/content/index.js
pages/asru-profiles-list/index.js
pages/asru-profiles-list/schema/index.js
pages/asru-profiles-list/views/index.jsx

Needs:
- https://github.com/UKHomeOffice/asl-internal-api/pull/139

Add former staff tab to staff directory

---

package-lock.json
package.json

🏠 housekeeping: pinned version of webpack to **working** version

bumped pages with hbaFilename changes

---

package-lock.json
package.json

Revert commit to use versions of asl- libraries just before ASSB-1345 bugfix

---

package-lock.json
package.json

https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4449

[ASL-4449] Update pages version

---

package-lock.json
package.json

Update dependency asl-components from 13.2.0 to 13.2.1; Update asl-internal-ui from 3.1.1 to 3.1.2

Update dependency asl-components from 13.2.0 to 13.2.1

---

package-lock.json
package.json

https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4457
Applies changes from https://github.com/UKHomeOffice/asl-projects/pull/903

[ASL-4457] Apply upstream changes

---

package-lock.json
package.json

Includes fixes for ASSB-1383, ASSB-1393, ASL-4457

ASSB-1383 Upstream deps.

---

package-lock.json
package.json

Bump asl-internal-ui from 3.1.2 to 3.2.0; Bump dependency asl-pages from 31.3.3 to 31.4.0; Bump dependency asl-components from 13.4.1 to 13.5.0

Bump asl-internal-ui from 3.1.2 to 3.2.0

---

package-lock.json
package.json

https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4537
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1385
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4527

Upstream deps for ASL-4527, ASSB-1385, ASL-4537

---

package-lock.json
package.json

fix protocols, asl-project bump up.

bump up asl projects for fixes.

---

package-lock.json
package.json

as/pages bump up, route path added.

---

package-lock.json
package.json

asl-page version bump up: v31.6.8

asl-pages ROPs field content change.

---

package-lock.json
package.json

@asl/projects: ^15.7.4,
@asl/service: ^10.6.0,

version updated,     @asl/pages: ^31.8.1,

---

package-lock.json
package.json

asl project and asl page updated version

Feature/update asl internal UI

---

package-lock.json
package.json

change highligts and hyperlink for tranfer project fix.

---

package-lock.json
package.json

asl-project and pages update
