UKHomeOffice/asl-internal-ui

Dockerfile
Images need to run with a numeric uid, and not a username.
As per https://github.com/UKHomeOffice/application-container-platform/blob/master/how-to-docs/pod-security-policies.md#runasuser
=> Use uid to run as user in dockerfile

.drone.yml, package-lock.json, package.json, tests/functional/config.js
So we know when deployments fail.
Also fix the deployment.
=> Add post deploy tests

lib/app.js
I assume the camelcase plugin for objection made this change from what it was before.
=> Fix casing of asru user flag

lib/app.js
The pages which load parameters from `req.establishmentId` and `req.profileId` were failing on account of those parameters being incorrectly named.
=> Ensure URL parameters that pages are expecting are passed

lib/urls.js, package-lock.json, package.json
The url that is hardcoded into the header did not match the configured url for loading the account mangement screens. Also the version of `@asl/service` installed was too old to support working notifications of a successful submission.
=> Fix account/profile edit journey

pages/project-versions/read/index.js
When viewing a granted licence then there is no open task associated with the project version, so reading its id fails. Check first that a task exists before trying to read it.
=> Don't assume an open task exists on a project

assets/sass/app.scss, package-lock.json, package.json, pages/profile/components/asru-admin.jsx, pages/profile/components/asru-roles.jsx, pages/profile/components/manage-roles.jsx, pages/profile/components/toggle-asru.jsx, pages/profile/content/index.js
=> ASRU user perms UI improvements

pages/profile/views/index.jsx
Using the length directly renders a zero out to the page when empty.
=> Cast establishments length to a boolean

pages/reporting/index.js
By moving the stream up to the top of the function then nginx should see a response much earlier, and prevent it throwing a 504 timeout error.
=> Pipe response immediately

assets/sass/app.scss, package-lock.json, package.json, pages/asru-assignment/schema/index.js, pages/search/views/index.jsx
~Waiting on https://github.com/UKHomeOffice/asl-pages/pull/362~
=> Separate establishment names in list view

pages/search/views/index.jsx
If a project doesn't have an expiry date - i.e. is a draft - then don't render an expiry date of 1st Jan 1970.
=> Don't render null expiry dates in project search results

assets/sass/app.scss, package-lock.json, package.json, pages/reporting/content/index.js, pages/reporting/index.js, pages/reporting/views/index.jsx
Adds output for a couple of headline figures and a breakdown of completed tasks by type for a specified date range.
Remove the UI for NTS summaries as that was a bit of a spike, but leave the rendering code in place.
=> Add metrics dashboard

pages/reporting/views/index.jsx
I was a little out when I set the dawn of time to 31st July 2019. There is one task that misses the cut.
Instead set the dawn of time to 1st January 2019.
=> Fix "all" metrics cut-off date

pages/profile/components/manage-roles.jsx, pages/profile/index.js
If no roles are selected then the body is empty and nothing is saved. Add a hidden field to the form so that the roles property is always set on the body and the payload is always sent.
=> Allow removal of all ASRU roles

tests/dedupe.sh
Having moultiple `react-router` instances in the dependency tree causes an issue, but the other versions are not being installed inside a `@asl/*` module because they're second level dependencies and so were not being detected by the previous script.
Make the match for other versions more liberal so that it correctly catches other instances in the tree.
Also add the correct instructions for resolving multiple `react-router` instances because for reasons `npm dedupe` doesn't cut it.
=> Modify react-router dedupe test path

config.js
It's easier to use the same event name and then segment by service name in sysdig.
=> Use same event key for internal and external error events

pages/create-establishment/index.js
* We were redirecting to establishment.search, however the path is search which defaults to est
=> Bugfix - fix redirect on est create cancel

pages/reporting/lib/nts-summary.js
The state of thinking around rendering rich text components into Word has moved on since this was originally authored. Copy the function from the projects implementation so it doesn't fail horribly on prod.
=> Get latest `renderNode` method from projects

pages/search/schema/establishments.js, pages/search/schema/profiles.js, pages/search/schema/projects.js
The `toCSVString` functions had the wrong arguments and so were throwing errors on export to CSV. Correct the arguments to `(value, row)`.
=> Fix CSV exports of search results tables

pages/licence-fees/index.js
If all the request is asking for is a new set of table data via XHR then don't make the additional API request to get the global totals as they will not be used.
=> Skip API request for global billing metadata if XHR request detected

lib/app.js
Privacy notice didn't seem to make sense to me between the billing and performance links, so re-order them so Privacy is first, then functional things are together.
=> Re-order footer links

pages/profile/content/index.js
There are some extra content fields defined in the task list content file that are useful when rendering task lists in profiles - specifically the extension to the deadline passed text. There's also some duplication.
Use all of the task list content in profile task lists.
=> Use all content from tasklist page

pages/nts/content/index.js
Also remove the incorrect bit about them being PDFs, because they're not PDFs.
=> Fix typo in NTS download page

pages/components/search-panel/index.jsx, pages/search/views/index.jsx
If a person has searched for a type of thing, remember their query if they move between different model types.
=> Remember search term when moving between model types

lib/routes.js
Moved project version router to top of routing stack so it doesn't inherit any breadcrumbs
=> Bugfix - project version routing

pages/profile/index.js
The allowed actions isn't always set at this point if passing through to a child route (it's handled downstream), so trying to filter it results in an error if routing to the downstream router.
=> Default allowed actions to an array

pages/downloads/index.js, pages/downloads/reports/index.js, pages/downloads/routes.js, pages/downloads/views/index.jsx
Map routes under `/downloads/:report` to API endpoints in the internal API and output whatever data is returned by the API endpoint as a CSV file.
Implement first report as `/downloads/pil-review`
=> Add routing for API driven report downloads

pages/nts/index.js
Currently if a proect has no title then it breaks the entire NTS download. There is one, but it's in ASRU TEST.
Filter out ASRU TEST projects because we don't want them anwyay, and handle the outside chance that a project ends up granted with an untitled version.
=> Handle untitled projects in NTS download

pages/nts/lib/renderers/v1.js
The key no longer has `-nts` on it. Remove that in the bulk NTS download renderer.
=> Fix NTS fate key in NTS bulk downloads

pages/nts/lib/rich-text.js
Images nested inside table cells fail the entire document with an error. This was fixed for the full application download, but the fix is complex, so for this context (and the literally one PPL it applies to) just fail with an inline error message and allow the rest of the content to render.
=> "Handle" images nested inside table cells

package-lock.json, package.json
I'm not sure those tests have been run in a very long time, and the dependencies are both slow to install and block updating to node@12
=> Remove functional testing libraries from dependencies

pages/nts-experimental/index.js
These will be removed once it's consolidated, but are necessary now to avoid repeating the entire renderer.
=> Some hacks to make one renderer work with both upstream data sources

pages/global-profile/views/index.jsx
For non asru users, the related tasks component is rendered by the global profile in pages, it should only be added here if the model is a asru user
=> Bugfix - related tasks.

pages/nts/index.js
In theory it should never happen that a project is granted with no title. In practice it did.
Make sure it doesn't crash NTS downloads.
=> Default project title in NTS download

pages/search/index.js, pages/search/search.js
This allows us to hit the same API endpoint, but with a flag to set experimental search if enabled on the downstream service.
Used a header rather than a querystring param because it is guaranteed not to interfere with the existing params in that case. It also is safer when deploying into environments without experimental search enabled than a separate endpoint.
=> Add a header if experimental search is enabled

lib/routes.js, package-lock.json, package.json
Need to mount the generic profile router first to ensure that req.profile is available downstream.
=> Re-order mounting profile routers

package-lock.json, package.json, pages/components/search-panel/index.jsx
If submitting a new search then remove any sort and pagination from the query string and revert to page 1 sorted by the default sort order.
This is specifically pertinent if the sort parameters have been inherited from a tasklist on the dashboard, and refer to sort columns and pages that don't exist.
=> Reset sort and query string parameters when performing a new search

pages/reporting/details/ppl-sla/content/index.js, pages/reporting/details/ppl-sla/index.js, pages/reporting/details/ppl-sla/schema/index.js, pages/reporting/details/ppl-sla/views/formatters.jsx
* deadlineDate (from deadline object) was removed in favour of deadlinePassedDate which stays set if the task is returned
* daysOverdue was removed because the calculation is not as simple as days before now
=> Various fixes for deadline management

pages/reporting/views/index.jsx
This allows them to be identified in integration tests that can assert on the numbers being correct.
=> Add classnames to metrics

pages/reporting/views/components/number.jsx
The code to insert commas into large numbers was removing the decimal places from the iterations count, where we need the exact value.
=> Preserve decimal places on metric numbers less than 1000

assets/sass/app.scss, pages/components/search-panel/content.js, pages/components/search-panel/index.jsx, pages/search/content/index.js, pages/search/content/projects-content.js, pages/search/index.js, pages/search/schema/index.js, pages/search/schema/projects-content.js, pages/search/views/components/project-search-result.jsx, pages/search/views/index.jsx
Creates `/search/projects-content` which exposes a UI for full content PPL searching.
This page is not currently linked in the navigation so we can safely deploy an alpha to prod.
=> Add "hidden" page for full-content PPL search

pages/search/views/components/project-search-result.jsx
We can't index protocols by id in elastic because that results in an arbitrarily large number of fields.
Instead use the index number to find them.
=> Lookup protocols by index and not id

pages/search/schema/projects-content.js
This means that if the datatable of results is exported as a CSV it includes some more useful metadata about the projects that match the query.
=> Add basic project fields to content search schema

assets/sass/app.scss, package-lock.json, package.json
The margin has been set to zero everywhere, and standard `h3` tags/styles are now used for the summary component.
=> Remove filter styles which are no longer needed

pages/components/search-panel/content.js, pages/components/search-panel/index.jsx
It's the same text in all cases, so there doesn't seem like much point in defining separately for all search types.
=> Simplify clear search link

pages/components/search-panel/index.jsx
There is no default filter applied when accessing search pages, so clearing the search should not add a filter.
"That doesn't sound like how I expected it to work. I think after clearing search results it should return to the default status - ie no filters." - Ben S [Slack, 2021-01-14]
=> Remove application of filter on "clear search"

pages/search/views/components/project-search-result.jsx
When clearing a null search the order of redux actions means that there's an infinitessimally small window in which results are returned but the search term state is not updated to prevent rendering results when no search term is entered.
This means that results with no highlighted terms are attempted to render, and so throw an error.
Handle the no highlight case to avoid this error.
=> Prevent error if no highlights returned

pages/reporting/index.js
If a user has selected a non-default tab on the performance metrics page then preserve that on submission of the filters form.
=> Preserve query string when redirecting metrics filter form

pages/search/schema/profiles.js
The sorting isn't working because the incorrect parameter name is being sent as the sort query when sorting by name. It needs to be `lastName` to match the field name in the data.
=> Define `sort` param for profile search table

pages/search/index.js
Currently the first click on the sorting header in a table is a no-op if it matches the default sort order.
By setting the default sort order explicitly then clicking on the name header the first time will reverse the sort order.
=> Add default sorting props to search results

pages/search/index.js
They override the sorting by natural search match once a query is made
=> Revert addition of default sort to search results

pages/reporting/index.js
Previously all project tasks on legacy projects were re-mapped to `legacy-project-${action}` which prevented RA tasks for legacy projects showing in the count for `project-grant-ra`.
Prevent mapping these as we don't want to split into new and legacy figures.
=> Don't split RA metrics into legacy and new

pages/reporting/details/task-list/report-filters.js
* schema version filter was being set to 1 for RA, causing legacy RA to be excluded
=> Return the correct tasks for RAs completed

pages/search/content/index.js
If a filter has been applied but no search term entered then don't show `X results for: ''`.
=> Don't include blank search term in search summary

pages/global-profile/content/index.js, pages/global-profile/index.js, pages/global-profile/pils/content/index.js, pages/global-profile/pils/index.js, pages/global-profile/pils/views/index.jsx, pages/global-profile/routes.js, pages/global-profile/views/index.jsx
This allows ASRU to see other PILs associated with a profile that may not show up in the users primary PIL page.
This includes cases where a single user has more than one PIL record, or has multiple training PILs.
=> Add global page with details of all PILs for a user

pages/reporting/details/task-list/content/index.js, pages/reporting/details/task-list/report-filters.js
When clicking from the metrics page into the list of ROP submission tasks a selection of errors were being thrown.
=> Fix errors loading list of ROP submissions

pages/licence-fees/establishments/schema/index.js
Since we're no longer doing an actual direct database query to get the data for this table we don't need to use the number of PILs as a proxy for the total fees for an establishment, and can sort on the total directly.
=> Allow total column to sort itself

pages/create-establishment/index.js, pages/create-establishment/views/index.jsx
Clicking the link resulted in an error page for a missing URL parameter. Add that to the redirect so it works correctly.
Also use `cancelLink` prop to pass the component so it renders nicely inline.
=> Fix cancel link in establishment create page

pages/search/content/projects-content.js
This was missing because the test data didn't include any completed transfers and the values are the result of elasticsearch aggregations.
=> Add label for transferred projects in search filters

pages/global-profile/views/index.jsx
These are no longer displayed on establishments or editable, so remove them from ASRU user profiles.
=> Remove ASRU affiliations from profile pages

pages/cjsm/content/index.js, pages/cjsm/index.js, pages/cjsm/schema/index.js
These are not mandatory, and one establishment has stopped using theirs so ASRU want to remove it.
* remove required validator
* accept an empty string in match regex
* send `null` to API if no value is entered so that database jsonschema validation does not try to match the format of `''` to an email
=> Allow removal of CJSM email from establishment

pages/common/content/index.js, pages/reporting/routes.js, pages/reporting/task-metrics/content/index.js, pages/reporting/task-metrics/index.js, pages/reporting/task-metrics/views/index.jsx
This page is not currently linked from anywhere and the URL `/reporting/task-metrics` will need to be manually entered in the address bar to access it.
Only the internal deadlines report is currently included. This report is only valid from when we started adding internal deadline dates to the task data, so it's limited to last month onwards.
The page currently looks like this:
=> Add a hidden page to download internal deadlines report CSV

.auditignore, .drone-1.0.yml, package-lock.json, package.json
Using the new `@lennym/ciaudit` module allows for an ignore list to be defined to allow certain advisories to not fail CI.
=> Update audit dependency to use ignorelist

pages/licence-fees/establishments/schema/index.js
This shows ASRU business support who might have out-of-date contact information or PO numbers.
=> Add updatedAt column to licence fees export

.auditignore, pages/search/schema/tasks.js
Update the schema in line with the task list schema to remove the `licence` column and prevent missing content error.
=> Fix missing content error on task search

pages/asru-workload/views/index.jsx
If moving between the returned and completed tabs on the ASRU workload page don't reset the dates back to the default.
=> Preserve date range when switching tabs

pages/search/content/profiles.js
This currently throws an error if a page of the search results includes someone with a PIL application in progress.
=> Add content label for pending PIL

pages/reporting/views/components/date-picker.jsx
Corrects the date picker being one day ahead by starting the week on Sunday rather than Monday
=> ASL-4245: Fix date picker being one day ahead

.drone-1.0.yml, package-lock.json, package.json
asl-deploy-bot seems to fail when using the new github token:
```
+ update --repo ukhomeoffice/asl-deployments --token ${GITHUB_ACCESS_TOKEN} --file versions.yml --service asl-internal-ui --version ${DRONE_COMMIT_SHA}
{ HttpError: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/git#get-a-reference"}
```
let's try with the previous one. if it fails we need to find out what's necessary to make this step pass
=> [ASL-4289] token wrangling for publishing 
